### ISSUE TITLE
Ignore timer?

### ISSUE THREAD

**Issue by Takst3in** [b0mbays/continuously_casting_dashboards#11]
Hey!

The description states that devices running any media/timers/etc will be ignored.
From what I understand of that, is that "If i have an active timer on the display" nothing will be casted to this device.

However, during today's dinner preparation, my Rice-timer were interupted several times.
I expected it to continue display the Timer, until atleast finished, but that did not work.

Any issues regaring that? 

Everything updated, latest OS/Integration/etc..

**Comment by b0mbays** [comment]
Hey @Takst3in sorry about my bad wording! The timer does go off the screen but it should continue in the background. You should still be able to ask "Hey Google, show my timer" And it will show. But it will go off eventually when the refresh comes around. The Google Hub unfortunately does not report a "status" when the timer is on the screen, so there is no way to stop this unfortunately 👍

**Comment by b0mbays** [comment]
Updated the documentation to fix the wording. Closing this issue 👍thanks!
