### ISSUE TITLE
Dashboard not being cast after some time

### ISSUE THREAD

**Issue by Thorvarium** [b0mbays/continuously_casting_dashboards#13]
Me and a friend we are both using your extension (thx again for the work) and we are both having an issue that after a while one of our dashboards just stop casting.

 I also noticed that once in a while it throws this error, not sure if it is related:

```
2023-04-27 11:12:21.684 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/subprocess.py", line 195, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 240, in start
    if (await self.check_both_states(device_name)) is None:
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 173, in check_both_states
    status_output = await self.check_status(device_name, dashboard_state_name)
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 115, in check_status
    stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by b0mbays** [comment]
Hey @Thorvarium, this is caused by some missing exception handling for the TimeoutError. Thank you for posting! 

I'm currently testing a new version that will be available in a couple of hours that _should_ stop this error from happening 😄 

I'll let you know when it's out!

**Comment by b0mbays** [comment]
The [update ](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.2.0) is out now.

Please restart home assistant, then check inside HACS for the update 👍 

Thanks!

**Comment by Thorvarium** [comment]
> The [update ](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.2.0) is out now.
> 
> Please restart home assistant, then check inside HACS for the update 👍
> 
> Thanks!

I updated it, thx!
I'll let you know if the dashboard stop casting again

**Comment by Thorvarium** [comment]
I also noticed that sometimes the cast information dnt have the "dummy bla bla bla", maybe that is related to the bug 
![image](https://user-images.githubusercontent.com/6555325/235007453-c9acf46a-02d0-48ed-99f6-82bd7990596f.png)

**Comment by b0mbays** [comment]
Sounds good 👍  Not sure about the status from that screenshot.. Which chromecast devices are you using?

**Comment by b0mbays** [comment]
See how it functions after the update and report back. The integration should be stable now

**Comment by iamer** [comment]
The latest version (1.2.0) is broken for me, had to rollback to the previous version 1.1.4
There were no logs or errors, it just never started casting at all..

**Comment by b0mbays** [comment]
That's odd! Can you post your config here? (You can hide any IP addresses etc)

**Comment by iamer** [comment]
I think I found the issue: I have both start_time and end_time set to 00:00 and that worked with 1.1.4 to continuously cast
The changes in 1.2.0 broke that, but it works if I set start_time 00:01 and end_time 00:00.

**Comment by b0mbays** [comment]
Sorry about that! I changed the condition for the integration is checking the timings and that must be it. I'll add a note to the readme for other users 👍

If you change the logging level to "debug" in the configuration it should have reported that the timings you have set were 'outside' the allowed cast times for your devices. 

Glad you found the fix! 😊

**Comment by iamer** [comment]
I suspected it was the issue by reading the diff of 1.2.0 to 1.1.4, and proved it by writing some test code. I had set the logging level to debug but couldn't find any messages in HA logs, maybe I was looking in the wrong place.
Maybe it could be more user friendly to have an "always on" setting instead :)

Anyway thanks for your fantastic work!

**Comment by b0mbays** [comment]
That is strange you're not seeing any logs... If you set it to debug in the continuously_casting_dashboards config then you should see lots of logs in just the regular home assistant logs in settings. Or inside the homeassistant.log file 🤔 If you go via settings you have to click/tap the "Load full logs" to see them.

I like the idea of an "always on" feature! I'll add that in the next version 😁

Thanks!

**Comment by Thorvarium** [comment]
So far the dashboard have been casting fine, this look fixed. Thanks!
