### ISSUE TITLE
Small issue with volume noises

### ISSUE THREAD

**Issue by Thorvarium** [b0mbays/continuously_casting_dashboards#14]
Sometimes without me doing anything I noticed that the volume of the google hubs jump to 5 and beeps. This even happen in the middle of the night.
Is there a way to mute those? Thanks

**Comment by b0mbays** [comment]
Could you post some of the debug logs for during the night and your config? Do you know if the volume jumping to 5 is when the display is supposed to be sleeping or are they being casted during this time?

**Comment by Thorvarium** [comment]
I will enable debugging and post here when I have it. I don't have sleeping time, I am casting 24/7

**Comment by b0mbays** [comment]
Are all of your devices enabled for 24/7 casting? I'm thinking there's some bug i've introduced potentially with the new version... I'll do some testing

**Comment by Thorvarium** [comment]
They are enabled 24/7 by my choice, I have start time 10:01 and end time 10:00

**Comment by b0mbays** [comment]
OK. The volume being set to 5 should only happen when a device is being re-casted to the display, so there must be some problem with the integration thinking your dashboard is not being casted and not picking up the 'Dummy' status. I see that you mentioned in the other issue that one of your displays was not reporting this 'Dummy' status. 

Can you check that the dashboard you are casting to your displays has the 'ha-catt-fix' as a resource? (dashboard -> three dots -> edit dashboard -> manage resources)

**Comment by Thorvarium** [comment]
Gotcha, I just rebooted HA to enable debug mode and right now all 3 google hubs are displaying the Dummy in paused state, but if I recall correctly, before rebooting all 3 had no Dummy being displayed in the card. Yesterday I noticed that some of the dashes also had no dummy being displayed in the card and I stopped casting on purpose to test... continuously_casting_dashboards casted back correctly. Maybe the issue is just that card display? Dunno.

I checked and the dashboards have the ha-catt-fix as resource. I will keep monitoring to see if the beep happen again and let you know with the logs

**Comment by b0mbays** [comment]
Hey @Thorvarium have you heard any more mysterious beeps since? 😅

**Comment by Thorvarium** [comment]
> Hey @Thorvarium have you heard any more mysterious beeps since? 😅

So far they have been quiet haha. Thanks for all the support

**Comment by b0mbays** [comment]
That's good to hear! I'll close this issue now 👍
