### ISSUE TITLE
No Casting

### ISSUE THREAD

**Issue by Fishairman90** [b0mbays/continuously_casting_dashboards#15]
Good morning, I am coming from another continuous casting project that worked pretty well but wanted to try this out. So im 99% sure it's not any of the "typical" casting issues.

Followed the instructions for the install
Added everything to my .config
Rebooted
Nothing happens. No attempts to cast. Cant find anything complaining in the logs.

**Comment by Fishairman90** [comment]
2023-04-30 12:10:38.471 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] state_triggers_map: {}
2023-04-30 12:10:38.472 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] monitored_entities: set()
2023-04-30 12:10:38.508 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Current local time: 12:10:38.507964
2023-04-30 12:10:38.508 INFO (MainThread) [custom_components.continuously_casting_dashboards.dashboard_caster] Local time is inside the allowed casting time for <Master_Bedroom_Display. Start time: 01:00:00 - End time: 23:00:00

**Comment by b0mbays** [comment]
Hey, can you post your config? Are there no more logs after the above logs? It should start to cast after printing that it's within the allowed casting time

**Comment by b0mbays** [comment]
I can see the name of the device in the log is:

<Master_Bedroom_Display

Are you sure that is what your device is named inside the devices settings or within the Google home app?

**Comment by Fishairman90** [comment]
![IMG_3726](https://user-images.githubusercontent.com/57339670/235364720-195e6e85-1efd-48bb-9efd-7b328a6c0053.PNG)

**Comment by Fishairman90** [comment]
Ahh I see what your saying.. the "<"

**Comment by Fishairman90** [comment]
Changing, let me see what happens

**Comment by Fishairman90** [comment]
Here is my full CONFIG

continuously_casting_dashboards:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
  start_time: '01:00' #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07.00" and can be individually overwritten per device below.
  end_time: '23:00' #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01.00" and can be individually overwritten per device below.
  devices:
    "Master_Bedroom_Display": 
        dashboard_url: "192.168.1.3:8123/lovelace/overview" 
        volume: 5
        start_time: '01:00' 
        end_time: '23:00'
    "Kitchen_Display": 
        dashboard_url: "192.168.1.3:8123/lovelace/overview" 
        volume: 5
        start_time: '01:00' 
        end_time: '23:00'

**Comment by b0mbays** [comment]
You don't need the "_" for the spaces in your names of the devices. Remove those and it should start casting 😁

For example:

"Office display":
    dashboard_url: "http://192.168.12.104:8123/nest-dashboard/default_view?kiosk"
    volume: 7
    start_time: "06.00" 
    end_time: "18.00"

**Comment by Fishairman90** [comment]
FYI I had to change all the "time values" from " to ' because it was throwing errors for all of them.

**Comment by b0mbays** [comment]
That's strange. Could you post the error log for the time value? Mine has " for the time values and no errors...

Did the above change fix things for you too?

**Comment by Fishairman90** [comment]
Here is the LOG
ValueError: time data '06.00' does not match format '%H:%M'


It's casting now, but coming to a login screen. "Baby steps"
Guess this casting method uses a different method of casting? Because I have never had to login.

I added "this" to my .config but now HA is booting in Safe mode. 

homeassistant:
# Note that this section is a subset of homeassistant: and is not tabbed all the way to the left like other things in configuration.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.19/32
        - 192.168.1.87/32
      trusted_users:
        IP_ADDRESS_1: 9183ba4e9axxxxxx5238d31af5
      allow_bypass_login: true
      # Note that bypass_login only works if one user is authorized
      
      
      Giving me this error:
      
      2023-04-30 12:46:32.254 ERROR (MainThread) [homeassistant.auth.providers] Invalid configuration for auth provider trusted_networks: extra keys not allowed @ data['trusted_users']['IP_ADDRESS_1']. Got '9183ba4e9a9a4exxxxd5238d31af5'
2023-04-30 12:46:32.255 ERROR (MainThread) [homeassistant.config] Invalid config for [homeassistant]: [IP_ADDRESS_1] is an invalid option for [homeassistant]. Check: homeassistant->trusted_users->IP_ADDRESS_1. (See /config/configuration.yaml, line 6).

**Comment by Fishairman90** [comment]
Ignore most of the last ^^^ 

Fixed that issue. It try to cast now, but just is a black screen and says "login" if you press login, nothing happens but a button pops up and says "start over"

**Comment by b0mbays** [comment]
Ahh there was a mistake in the readme! It looks like I was using a dot (.) Instead of (:) between the timings which was causing the error that you saw. I've the examples on the readme now. Thank you!

As for your "login" error, that's a case of the trusted networks not working for the devices IP address. The long number and characters you sent represents an ipv6 IP address (I think...). Is there a way you can force your router to use ipv4 for your devices? That might be the issue.

For example, my displays are in the format of "192.168.1.200" etc

**Comment by Fishairman90** [comment]
oof welp, im locked out of my HA on all devices..

**Comment by b0mbays** [comment]
Ignore my last comment, I misread your config. It looks correct, other than which IP address are you using for the trusted users?

It should be the device IP (192.168.1.19/32) and then the user ID. So, you require two entries for both of your devices

**Comment by Fishairman90** [comment]
Finally got back in haha... I have this setup in my config

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.87/32
        - 192.168.1.88/32
      trusted_users:
        192.168.1.87/32: userid1
        192.168.1.88/32: uderid1
      allow_bypass_login: true
      
      
      It still is manually requiring me to click login each time.

**Comment by Fishairman90** [comment]
Made it! haha

**Comment by Fishairman90** [comment]
Finally fixed 90% of my issues and have one auto logging in. But for whatever reason now it's only working on one of them. 

continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
  start_time: '01:00' #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07.00" and can be individually overwritten per device below.
  end_time: '23:00' #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01.00" and can be individually overwritten per device below.
  devices:
    "Master Bedroom Display": 
        dashboard_url: "http://192.168.1.3:8123/lovelace/overview" 
        volume: 5
        start_time: '01:00' 
        end_time: '23:00'
    "Kitchen Display": 
        dashboard_url: "http://192.168.1.3:8123/lovelace/overview" 
        volume: 6
        start_time: '01:00' 
        end_time: '23:00'

**Comment by Fishairman90** [comment]
Update, they seem to be working now.. Rebooted both Google Homes.

**Comment by b0mbays** [comment]
That's great to hear! 😁

You could also check out kiosk mode for making the dashboards full screen if that's something you're after, theres a link in the requirements section👍
