### ISSUE TITLE
Integration is not currently compatible with HA 2023.5.0

### ISSUE THREAD

**Issue by Wheemer** [b0mbays/continuously_casting_dashboards#17]
Getting this error:

Setup failed for custom integration ha-continuous-casting-dashboard: Requirements for ha-continuous-casting-dashboard not found: ['catt==0.12.10'].

What are the prerequisites? It was working but suddenly is not, I don't think I changed anything.

**Comment by b0mbays** [comment]
Hey @Wheemer , that looks like the old name of the integration on an older version. Can you update or remove + reinstall the integration?

It should be called "continuously_casting_dashboards" in the logs and inside your configuration.yaml.

**Comment by Wheemer** [comment]
Setup failed for custom integration continuously_casting_dashboards: Requirements for continuously_casting_dashboards not found: ['catt==0.12.10'].

**Comment by b0mbays** [comment]
That's odd. And you say this was working previously and then stopped working? Could you post your config for the integration?

Also, what version of HA are you running?

**Comment by Wheemer** [comment]
Yes it was working, however it always stopped, never was continuous for long. However it's been getting this error for a few days now.

continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between devices
  start_time: "06:30" #Required: Start time of the casting window (format: "HH:MM")
  end_time: "02:00" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  devices:
    "Family Room display": #Required: Display name of your device. Find this under device settings -> Information -> Device Name
        dashboard_url: "http://192.168.0.108:8123/lovelace/default_view?wp_enabled=true" #Required: Dashboard URL to be casted

**Comment by b0mbays** [comment]
That's frustrating! The integration was never really stable until it moved to the new name of 'cotinuously_casting_dashboards' so that's why it would have never been continuous for long. (hopefully!)

What device are you casting to? Can you change the logging_level to 'debug' and see if you get any more logs? Or does the integration just fail to start?

Could you also try uninstalling the integration, temporarily removing the config for the integration, re-installing and then adding the config back?

**Comment by Wheemer** [comment]
No it doesn't start at all. I forgot to mention I am on the latest beta version of HA.

I did completely remove the integration and settings and reinstalled when you mentioned I had an old version.

Do I need dashcast installed?

**Comment by b0mbays** [comment]
The beta shouldn't make a difference... Could you try installing dashcast? If that's the issue then that's my bad entirely! 

The error above suggests 'catt' is not compatible with whichever version you are running... which doesn't make sense. Try installing dashcast first 😄

**Comment by Wheemer** [comment]
I just uninstalled dashcast, as it was previously installed. I thought it might be conflicting. Still won't run.

I see this in the logs:

Unable to install package catt==0.12.10: ERROR: Cannot install catt because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip

**Comment by Wheemer** [comment]
Same errors after reinstalling dashcast again.

**Comment by b0mbays** [comment]
There must be something new in the HA Beta that is causing this dependancy error.

Do you have access to a terminal that is logged into HA? If so, could you try the following command:

`pip install catt`

or

`pip3 install catt`

And post the output?

Thank you! 

I'll also try and upgrade to the Beta.

**Comment by Wheemer** [comment]
I have uninstall pyscript from HACS and AppDaemon addon to see if they were interfering. Are those requirements?

**Comment by b0mbays** [comment]
Okay I have updated to the Beta and I see the same error. We'll have to wait for the developer of 'catt' to update their packages when a newer stable release of HA is released.

If you want to use the integration i'd suggest to downgrade to a 'stable' release of HA. You can either restore from a backup (if you have one) that is using the current stable HA version.

Or you can manually downgrade your HA version easily from within the HA terminal with the following command:

`ha core update --version  2023.4.6`

Here is what mine looking like when I upgraded, but you can do the same to go to a lower version:

![Screenshot 2023-05-03 at 16 37 24](https://user-images.githubusercontent.com/55556007/235966925-091aa181-417c-4eaa-bdbb-d40cca9b4bcc.png)

**Comment by Wheemer** [comment]
Thank you, it is working now. I will refrain from updating this instance.

And I believe it would be helpful to add dashcast to the requirements.

Also I tried to setup an input boolean to turn the casting on and off, however that doesn't seem to work. It casts all the time regardless of the state of the boolean.

Here's my setting again:

`continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between devices
  start_time: "06:30" #Required: Start time of the casting window (format: "HH:MM")
  end_time: "02:00" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  devices:
    "Family Room display": #Required: Display name of your device. Find this under device settings -> Information -> Device Name
        dashboard_url: "http://192.168.0.108:8123/lovelace/default_view?wp_enabled=true" #Required: Dashboard URL to be casted
  state_triggers:
    "Family Room display":
        - entity_id: "input_boolean.cast_to_hub"
          to_state: "on"
          dashboard_url: "http://192.168.0.108:8123/lovelace/default_view?wp_enabled=true"`

**Comment by b0mbays** [comment]
Btw, the state trigger feature won't be able to 'turn off' the dashboard. It's only used for casting _to_ a display when an entity changes. If you want to turn off the display with an entity, you could set up an Automation through HA to turn off the Google Cast device itself (which will return it to the clock). 

However, if you this integration running and it's within the time range, then it will try to cast to the display again 😄

**Comment by Wheemer** [comment]
OK I have given up on the boolean.

The code gets messed up even while using the code quotes, so this editor has issues.

It's all good now, I'm just keeping an eye on it to see if it stops casting now.

Thanks for you help and contribution to the community.

**Comment by Fishairman90** [comment]
Can confirm.. just installed HA 2023.5 and immediately started having issues with this. :-/

**Comment by b0mbays** [comment]
Ahhh no! Okay i'm working on a fix now for the new version. 

Just pushed a new update for an unrelated unhandled exception that was causing some problems, but i'll get a compatible version out soon!

**Comment by b0mbays** [comment]
Well... I've tried a few things (such as forking the catt package) but alas it's not working. I'm reverting back to 2023.4.6 and will wait for a new release of catt.

I've raised an issue [here](https://github.com/skorokithakis/catt/issues/428) and will get an update out as soon as it's working 👍

**Comment by klasenby** [comment]
Thanks for the heads up on this, I'll wait to upgrade as well

**Comment by Thorvarium** [comment]
Same here, I reverted to 2023.4.6 for now. Thanks!

**Comment by se-bastiaan** [comment]
For a temporary fix:

CATT needs to have PEP 517 build-system settings to make sure pip can install it from git
https://github.com/se-bastiaan/catt/commit/e3ef4ee25da5f04dd43c79040864efcced44059d
And the version here can just be a tag
https://github.com/se-bastiaan/continuously_casting_dashboards/commit/1a9a2611efd497f182ba5bb6375ce6e49e06bc6f

**Comment by b0mbays** [comment]
Ahh thanks for the info! I'll try that out later on if there isn't a new pip version by then. It looks like they're pushing one now 👍 

I'll do some testing with the new version and get an update out asap!

**Comment by b0mbays** [comment]
New update is out with added support for 2023.5.x, thanks everyone for their help!

**Comment by Thorvarium** [comment]
hey @b0mbays, I am having now after updating HA and CCD:
![image](https://github.com/b0mbays/continuously_casting_dashboards/assets/6555325/47b9af35-cc8b-45ea-bc1e-ab8239160f8a)

**Comment by b0mbays** [comment]
Ah, you'll need to do a full system reboot for HA. After it has rebooted, it should use the new version

**Comment by Thorvarium** [comment]
It do not let me reboot without fixing this issue lol

**Comment by b0mbays** [comment]
You can, there's a 'restart' and 'reboot' inside settings. The reboot doesn't do any checks. 

If you can't find it Google is your friend 😁

**Comment by b0mbays** [comment]
That's great to hear! I'll make a note that some users may need to reboot 👍
