### ISSUE TITLE
CCD interrupts music playing if device is part of a group

### ISSUE THREAD

**Issue by klasenby** [b0mbays/continuously_casting_dashboards#21]
I have a Chromecast group called "main floor". If I start playing music on the group, it is interrupted by the dashboard cast. 

Presumably this is because the device I'm casting the dashboard to is not the device name that's playing, it's the group it's part of. 

Hopefully there's a way to check the group membership

**Comment by b0mbays** [comment]
Hi, I haven't tried creating a group within Google Home and if it's compatible with this integration but I can take a look when I get some time soon and figure out a solution 👍

**Comment by goldrake1981** [comment]
Hello and congratulations on this project. I also have several Nest Hubs in my house and when I try to play music on them the CCD stops the music

**Comment by dan0878** [comment]
I have fudged this to work as I was getting complaints from the family! The catt 'status' does not return anything useful when the device is in group mode. However, if you call catt 'info' if will return additional information that can be used to detect whether the device is active. I have added some code to detect whether the display_name = Backdrop which is my screensaver, this will be something else when active. If this is showing then we assume the device is doing nothing and therefore allow the cast to occur.

**Comment by goldrake1981** [comment]
Can you share the changes for those like me who are not capable? Thanks

**Comment by LukasSolf** [comment]
@b0mbays any news on when this topic will be fixed? Currently, CCD can't be used because the media being played is always stopping if the device is assigned to a group.

**Comment by b0mbays** [comment]
@LukasSolf Apologies. I'll take a look today

**Comment by b0mbays** [comment]
I have a fix working for this, I'll upload a new release tomorrow! 🚀 

You will be able to supply the name of a speaker group per device. I just need to do some more testing in the morning before releasing 😄

**Comment by b0mbays** [comment]
> I have fudged this to work as I was getting complaints from the family! The catt 'status' does not return anything useful when the device is in group mode. However, if you call catt 'info' if will return additional information that can be used to detect whether the device is active. I have added some code to detect whether the display_name = Backdrop which is my screensaver, this will be something else when active. If this is showing then we assume the device is doing nothing and therefore allow the cast to occur.

The incoming fix will work by calling the speaker group using 'catt -d <speaker-group-name> status' which is given per device in the config and if it's playing, then skip the cast. Google creates a new 'device' essentially (just like another hub) when you create a new group which we can then call and ask for it's status 👍

**Comment by LukasSolf** [comment]
Awesome, thanks for the fast reaction! I'll give it a try later.

**Comment by b0mbays** [comment]
I have published a new release [v1.3.1](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.3.1) - after updating to the new version, update your configuration then restart again.

Let me know if you have any issues 👍 CCD should now skip any devices that are playing audio on a speaker group.
