### ISSUE TITLE
High CPU usage between end_time and start_time

### ISSUE THREAD

**Issue by chrixzy23** [b0mbays/continuously_casting_dashboards#24]
Between the global end_time and global start_time the cpu usage is at 30% if no casting is active. Between start_time and end-time the cpu usage is at 2% if casting is activ. I use one Goolge Nest Hub 2. generation.  

Hopefully there is a solution to this problem.

**Comment by b0mbays** [comment]
Hi, are you using the latest version of the integration? I released an update (v1.2.5) that _should_ have fixed this problem.

**Comment by chrixzy23** [comment]
Yes, I was using the previous 1.2.4 version and didn't notice the new update. With version 1.2.5 it works fine and CPU usage is normal during sleep time. Thank you for the update and the great work.
