### ISSUE TITLE
Error when adding trusted networks to config.yaml

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [b0mbays/continuously_casting_dashboards#26]
Hello @b0mbays

If i try to add trusted networks to my config,yaml as the exmaple given below using my own credentials I get errors caused by external url or auth providers OR as soon I type "homeassistant:" I already get the red exclamation mark in config editor that is not correct config .... what am I doing wrong? and do i need to add CATT manual by using "pop3 install catt" in terminal? I did read in other issue it get installed with install of integration. 

This is my install information: 

Version | core-2023.7.2

Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.4
Operating System Family | Linux
Operating System Version | 6.1.34
CPU Architecture | aarch64
Timezone | Europe/Bucharest
Configuration Directory | /config

homeassistant:
  external_url: "<your-external-url-for-home-assistant"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.12.236/32 #These are my display IP addresses, replace them with your own (including the /32)
        - 192.168.12.22/32
        - 192.168.12.217/32
      trusted_users:
        192.168.12.236: <your-user-id>
        192.168.12.22: <your-user-id>
        192.168.12.217: <your-user-id>
      allow_bypass_login: true
    - type: homeassistant

**Comment by smarthomefamilyverrips** [comment]
@b0mbays 

already solved I not realized I already had "homeassistant:" added in my config.yaml

**Comment by b0mbays** [comment]
Glad you got it sorted! Let me know if you have any other issues 👍
