### ISSUE TITLE
Integration keeps setting Hub volumes to "0"

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [b0mbays/continuously_casting_dashboards#28]
@b0mbays ..... for whatever reason the integration keeps set my hubs volume on "0" no idea why.... i did try leave "volume:" out of config yaml, i did try to add "volume:" but add no value .... still it not leaves my volume untouched

if i set a value for volume it does set that volume, but i just want my volume to be untouched.

any idea?

**Comment by b0mbays** [comment]
Hi @smarthomefamilyverrips - If you exclude the volume from each individual config for each display then it should always use the volume that the hub was before the casting. 

However, depending on the firmware/device sometimes HA is unable to read the volume from the device before the casting so this will fail and revert to a default value of 5. Not sure why yours is remaining on 0 though... You might just have to use a value for the volume unfortunately 👍

**Comment by smarthomefamilyverrips** [comment]
Thanks for the support @b0mbays !
