### ISSUE TITLE
Error after last Update

### ISSUE THREAD

**Issue by gencure** [b0mbays/continuously_casting_dashboards#32]
If i run the configuration check I got this error:
Integration error: continuously_casting_dashboards - Requirements for continuously_casting_dashboards not found: ['PyYAML==6.0'].

**Comment by b0mbays** [comment]
Hi, please reboot your home assistant instance after updating. HA is unable to verify the configuration as it requires to be updated before doing so. Forcing a reboot is the only way to get this working (as long as you have updated both CCD and HA)👍

**Comment by b0mbays** [comment]
Closing this issue. If you still have issues after a reboot, please re-open the ticket.
