### ISSUE TITLE
Camera sgream cast

### ISSUE THREAD

**Issue by Takst3in** [b0mbays/continuously_casting_dashboards#34]
Hi!

This might be outside of the spec of the integration, however some solutions for streaming a camera stream to Nest Hubs are not ideal when using it as a baby-monitor.

Is there a possibility to extend the function of your great integration to stream a camera stream?

The issues that are common with using other solutions is that streaming starts without sound (muting enabled/etc), and the ability to control hours/etc is great.

Offcourse, i have already tested this integration to stream a dashboard in panel mode, with only a card for the stream, but what i am looking for is an ability to cast the  stream directly, and not within another dashboard/card.

**Comment by b0mbays** [comment]
Hey @Takst3in , sorry but this would be outside the spec of the integration unfortunately. This integration only casts webpages - I would look into DashCast/CATT casting CCTV streams individually.
