### ISSUE TITLE
How to cast to the same device at different time different dashboard

### ISSUE THREAD

**Issue by sebastian-bugajny** [b0mbays/continuously_casting_dashboards#35]
Hi There,

Is is possible to cast another dashboard oto the same device at deterrent period of time. I would like to have something like:

continuously_casting_dashboards:
  logging_level: info
  cast_delay: 45
  devices:
    "192.168.10.5":
       - dashboard_url: "http://192.168.10.100:8123/google-nest/pv?kiosk"
         volume: 4
         start_time: "07:00" 
         end_time: "22:00"
      - dashboard_url: "http://192.168.10.100:8123/google-nest/cameras?kiosk"
         volume: 1
         start_time: "22:00" 
         end_time: "07:00"

**Comment by b0mbays** [comment]
Hey @sebastian-bugajny this should be possible. I'll take a look when I get some time over the next couple days and get this implemented for you 👍

**Comment by sebastian-bugajny** [comment]
That would be great. Thanks in advance.

**Comment by sebastian-bugajny** [comment]
Hey @b0mbays any news re implementation of this extra functionality ?

**Comment by b0mbays** [comment]
I will try and look into this for you soon, apologies!

**Comment by purplefis** [comment]
Hey

I had the same need at added to b0mbays excellent code to achive my goal. I've created a pull request for b0mbays if he feels this is the right way to incorporate the enhancements. @sebastian-bugajny you can check out my changes in the pull request section.

**Comment by sebastian-bugajny** [comment]
@purplefis I've tested your changes and it works very well on my HA deployment. It's switching between dashboards at specified times on the same device. Good job. 
@b0mbays I hope it will be released shortly so I can have it deployed properly

**Comment by b0mbays** [comment]
> @purplefis I've tested your changes and it works very well on my HA deployment. It's switching between dashboards at specified times on the same device. Good job. 
> @b0mbays I hope it will be released shortly so I can have it deployed properly

Great work @purplefis! And thanks for testing it out @sebastian-bugajny. Apologies for not having the time myself to implement this.

I'll get this in today and create a new release for it 👍

**Comment by b0mbays** [comment]
New [release](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.2.7) created, thanks again @purplefis!

Please check for updates within the HACS store for the new tag: **1.2.7**

**Comment by b0mbays** [comment]
Hmm.. I have an error after updating. I'll try and fix this when I can! 
![Uploading Screenshot 2023-12-15 at 20.01.10.png…]()

**Comment by b0mbays** [comment]
@purplefis Do you not have the same error? Could you post your config with the correct formatting too. Thanks!

**Comment by b0mbays** [comment]
@purplefis Okay I see the issue now, I had to change the structure of the 'devices' section from a dictionary of dictionaries to a dictionary of lists of dictionaries... (by adding the '-' on the dashboard_url line). If we don't do that, the error occurs. I'll add some error handling for that.

I think it's okay, although anyone updating would have to also make this change. I can include it in the update notes 👍

**Comment by b0mbays** [comment]
New [release](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.3.0) with instructions for the user.

**Comment by purplefis** [comment]
> New [release](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.3.0) with instructions for the user.

Sorry for not getting back !
