### ISSUE TITLE
is CATT included or do I need to install it first?

### ISSUE THREAD

**Issue by cozarkd** [b0mbays/continuously_casting_dashboards#4]
Hi,

I was reading the requeriments and I thought that CATT was included in your project but I can't see anything working. Should I install it manually? I'm running HA in a TrueCharts chart in Truenas scale.

Thanks, If this works would be what I was looking for days.

**Comment by cozarkd** [comment]
Sure, I'll add a few lines before to check hierarchy.

Debug logs are on terminal or HA web?

ty

```
binary_sensor:
  - platform: ping
    name: Internet
    host: 8.8.8.8
    scan_interval: 15


homeassistant:
# Note that this section is a subset of homeassistant: and is not tabbed all the way to the left like other things in configuration.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24 #to not lose access from local devices (not sure if the best way)
        - 192.168.1.11/32 # my google hub
      trusted_users:
        192.168.1.11: ecb214ecXXXXXXXXXX7cb48ac9056d0

      allow_bypass_login: true
      # Note that bypass_login only works if one user is authorized
    - type: homeassistant

ha-continuous-casting-dashboard:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between devices
  start_time: "08:30" #Required: Start time of the casting window (format: "HH:MM")
  end_time: "02:00" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  devices:
    "Google Hub": #Required: Display name of your device. Find this under device settings -> Information -> Device Name
        dashboard_url: "https://ha.mydomain.com.es/dwains-dashboard/home" #Required: Dashboard URL to be casted
```

**Comment by cozarkd** [comment]
So I tried to change the name in the Google Nest Hub to avoid weird characters.
Keeps saying that can't find device.

Not sure what to try now, I restarted HA and disconnected Google Nest Hub and connected again.

**Comment by b0mbays** [comment]
Can you post the configuration you have for the integration inside the [ha-continuous-dashboard](url) section?

**Comment by b0mbays** [comment]
OK, your config looks good other than the dashboard url should be your local IP for your Home Assitant instance. For example, mine is: `192.168.12.104` rather than the URL to your externally hosted HA instance.

We can do some testing with CATT to see if your devices are accessibile over your network from Home Assistant, open up the 'Terminal and SSH' for Home Assistant (or any other way that you use a terminal within Home Assistant)

And try the command:

`catt scan`

And then post the output of that here? It should show any Chromecast devices on your network.

**Comment by cozarkd** [comment]
well, I have a problem I guess. I'm using a dns resolver locally so that's my local URL too but I can't change DNSs on my router and I guess I can't on the device manually. So, if I expose the IP too, then I guess I can't use my SSL certificate...
I'll try just in case.

About the terminal I'm not sure how to do it because I don't have access to HA apps. I'll ask in the Truecharts community about that because it seems I don't have catt in the terminal I use.

I'll post back.

**Comment by cozarkd** [comment]
Yes, that's it. I just needed to "login" first. But... my HA user doesn't seem to work. I'm trying with the Owner user I use inside Home Assistant dashboard. Should I use a different user?

And I think I managed to change the DNS on the router, not sure if the Google Hub will get it tho. Maybe I have to do a factory reset or wait to the Google Hub DNS to update after a while.

**Comment by b0mbays** [comment]
Can you post a screenshot of this terminal you are using? Mine doesn't ask for any users/passwords when logging in with the terminal. I'm thinking it might be different if you are using a truenas setup..

**Comment by cozarkd** [comment]
I'm waiting for the community to tell me something about this. I'm confused, I can't use the truenas user neither home assistant user...
![Captura de pantalla 2023-03-31 a las 16 10 27](https://user-images.githubusercontent.com/6465435/229144193-92999073-4369-4521-b8e4-cf5eb0406c41.png)

**Comment by b0mbays** [comment]
Hey, did you get anywhere with this?

**Comment by klasenby** [comment]
> Hey, did you get anywhere with this?

Adding some of my experience running HA and this integration in Docker on my Synology NAS, sounds similar to Truenas. 

I had already installed catt in the HA docker instance and used it to cast a website as a test (catt -d "ip address" cast_site http://www.google.com)
"Catt scan" doesn't return anything, I'm not sure why, possibly because of the NAT config of the docker container
I have to cast to the IP address of the Google Hub, then it works fine. 
I have DHCP reservations setup for all my hubs so I know their IP.

**Comment by cozarkd** [comment]
Well, I changed to IP and google.com (as dashboard) cast works perfect now.

But, for some reason, I can't use the dashboard url. My Home Assistant is reachable through internet tho...

I get DashCast splash screen and gets stuck there.

**Comment by b0mbays** [comment]
That is odd. So you can access it fine on your home network.. But your cast doesn't like it. Is Home Assistant accessible by a direct IP on your home network? Check your router and see if you can see it anywhere?

@klasenby If you are using a similiar setup, do you use a direct IP address for the dashboard URL in the config?

**Comment by klasenby** [comment]
I do use a local IP address for the dashboard url, its the IP address of my NAS.

172.16.x.x is the IP range for Docker running on the NAS:
![image](https://user-images.githubusercontent.com/4096799/229809499-7bf05e2f-9b39-43cb-9819-e06fe2ca2d89.png)

10.30.0.10 is the IP address of my NAS that hosts the Docker images behind a NAT, port 8123 is passed through to the HA Docker container:
![image](https://user-images.githubusercontent.com/4096799/229810751-286001ac-3960-4c9a-a7be-e55e3d3a35a7.png)

dashboard_url: "http://**10.30.0.10:8123**/lovelace/default_view?kiosk"

**Comment by cozarkd** [comment]
My setup is something like this:

Global:
- Public domain on Cloudflare with A record pointing to my network IP.

LAN:
- DNS resolver on my NAS on 192.168.1.60
- Router with automatic DNS from ISP (doesn't seem to work well with my DNS)
- My Mac and Android phone with custom DNS (192.168.1.60)
- So when I access https://ha.mydomain.com it resolves locally and uses my cloudflare certificate to access with SSL.

Internet:
- Cloudflare resolves the DNS. I have a CNAME record like ha.mydomain.com
- My NAS resolves that somehow with Traefik/Blocky and I can access ha.mydomain.com

So the local address and Public address is the same, I double checked with friends devices that the public URL is accessible without any device DNS configuration.

Is it ok to send a http url instead of https to the Hub?
I could access locally with ip:port but then I don't have a SSL connection. If that's a must for this to work I need to use the public domain and Google Hub would go through Cloudflare first because I think I can't change DNS on the Google Hub or router.

**Comment by klasenby** [comment]
On your phone, can you get to this URL? 

http://192.168.1.60:8123/lovelace/default_view

If you can, then use that to cast to your hub.
