### ISSUE TITLE
HASS 2024.2.0 - CCD stuck at login screen

### ISSUE THREAD

**Issue by doenau** [b0mbays/continuously_casting_dashboards#44]
After updating to 2024.2.0 this morning, my google nest hubs just sit at the HASS login page but with no selectable user or input. 
I’ve checked the trusted networks config and tested the auto login using my phone browser (and logging out which then automatically logs back in) - so I think the trusted networks is working ok generally.

**Comment by b0mbays** [comment]
Hi @doenau after updating we are not seeing any issues. Could you change the logging_level in the CCD config to "debug" and then post your logs here? Thanks!

**Comment by doenau** [comment]
Ok so it has magically fixed itself between when i left the house this morning and when i got to work and checked the logs (and visual confirmation from someone at home), but it definitely wasn't working all day yesterday after the update :(

**Comment by b0mbays** [comment]
@doenau No problem! Sometimes a network issue can stop the dashboards from casting. Usually a restart of HA fixes this though in my case 👍
