### ISSUE TITLE
Sample missing colon

### ISSUE THREAD

**Issue by klasenby** [b0mbays/continuously_casting_dashboards#5]
First off, this is a fantastic integration, thank you!

I got an error reloading HA after adding entity state change code, looks like your sample is missing a colon on the <display name> line?

ha-continuous-casting-dashboard:
  # ...
  state_triggers:
    "<Display_Name>"
        - entity_id: "<Entity_ID>"
          to_state: "<To_State>"
          dashboard_url: "<Dashboard_URL>"
          time_out: <Timeout_time> #Optional!

Should be:

ha-continuous-casting-dashboard:
  # ...
  state_triggers:
    "<Display_Name>":
        - entity_id: "<Entity_ID>"
          to_state: "<To_State>"
          dashboard_url: "<Dashboard_URL>"
          time_out: <Timeout_time> #Optional!

**Comment by b0mbays** [comment]
Thank you, I'm happy you like the integration! How is it working for you in terms of stability? I've been trying to improve that with the recent updates and things have been stable for me now for 2 days with no integration crashing errors.

Good spot on the README mistake! I'll update the this now as I must have missed it 😁

**Comment by klasenby** [comment]
Stability has been good with 1.1.2, I still don't have the triggers working, that's today's task.

I'm casting to a Lenovo display by IP address because catt couldn't seem to find device names, and I didn't enable external access but I have a Nabu Casa account. 

Is there a way to have multiple time windows? Like cast 6am to 9am and then 6pm to 9pm?

**Comment by klasenby** [comment]
That was quick, triggers are working now.  
Reminder to myself that device states are case sensitive.

**Comment by b0mbays** [comment]
That's great to hear! Good to hear that casting by triggers was easy to setup too.

I like the idea of custom time windows, I'll look into that next for the next version. I also thought the ability to define custom time windows per device would be a good idea too.

**Comment by b0mbays** [comment]
Hey @klasenby I had to rename the integration (to match home assistant standards) so the latest update requires you to make some changes to the configuration.yaml file as explained in the update notes. I had some issues updating (the integration would not start) and I had to uninstall the integration completely, reboot and then re-install it.

I'm now thinking a full reboot may have solved this problem after updating and renaming the integration inside the config file.

Could you let me know if you do update if that worked for you? Thank you so much!

**Comment by klasenby** [comment]
I saw the notification and change log in HACS. I upgraded, edited my config file, restarted HA and all seems good, no issues!

**Comment by b0mbays** [comment]
Amazing. Thank you for that feedback! I must have gotten into a bit of a mess with the amount of different versions I have for testing purposes in my file system!

Really appreciate you reporting back 👍 thanks!
