### ISSUE TITLE
Error during setup of component conintuously_casting_dashboards

### ISSUE THREAD

**Issue by blindeslakkie** [b0mbays/continuously_casting_dashboards#51]
Hi

I get the error below, this used to work. Don't even know where to start looking for this problem.
---------------------------------------------
Home Assistant Core: Version: 2024.3.0
Home Assistant Operating System: Version: 12.0
Home Assistant Supervisor: Version: 2024.02.1
Continuously Casting Dashboard: v1.3.0

---------------------------------------------

Invalid config
The following integrations and platforms could not be set up:

[continuously_casting_dashboards](https://github.com/b0mbays/continuously_casting_dashboards) ([Show logs](http://192.168.88.105:8123/config/logs?filter=continuously_casting_dashboards))
Please check your config and [logs](http://192.168.88.105:8123/config/logs).

--------------------------------------------------------

Logger: homeassistant.setup
Source: setup.py:390
First occurred: 12:11:01 PM (1 occurrences)
Last logged: 12:11:01 PM

Error during setup of component continuously_casting_dashboards
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/__init__.py", line 20, in async_setup
    caster = ContinuouslyCastingDashboards(hass, conf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 30, in __init__
    device_info.get("start_time", global_start_time), "%H:%M"
    ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by b0mbays** [comment]
Did you recently update the integration?

Could you post your config for the integration inside the `configuration.yaml `or check that this change is completed:

https://github.com/b0mbays/continuously_casting_dashboards/blob/main/docs/update-help-1.3.0.md

**Comment by b0mbays** [comment]
Great to hear 😄 No problem at all. It can be easily missed when updating!
