### ISSUE TITLE
Not working after Updating HA 

### ISSUE THREAD

**Issue by maxakash** [b0mbays/continuously_casting_dashboards#53]
Hi @b0mbays 
I have 7 nest hubs on which casting was working fine. But since I have updated, casting only works on 5-6 nest hubs at a time. 
Please look into it.

Here is the error from logs
![image](https://github.com/b0mbays/continuously_casting_dashboards/assets/17406944/fc8cfac5-2b56-476f-9d73-b610be4fdba7)

**Comment by b0mbays** [comment]
Hey @maxakash I unfortunately don't have more than 5 hubs to test this out on but I'll try and flook into this. I occasionally get timeout errors for a couple of my devices, and a simple restart of HA fixes the casting. I've found i'm doing this maybe one a week. Does your issue get fixed if you do a restart?

**Comment by maxakash** [comment]
Hi @b0mbays restarting HA fixes the issue but I have to restart couple of times daily.
Also I have warning or debus as log, my CPU usage rises to around 90%. 
Thanks

**Comment by b0mbays** [comment]
Could you try increasing the cast_delay? What do you have that set to currently?

**Comment by maxakash** [comment]
> Could you try increasing the cast_delay? What do you have that set to currently?

My cast delay is set at 45. I will increase it to 60.
I also have one doubt. One day my HA went offline for few hours but HA dashboard  stayed casted on the nest hubs. I thought Nest hubs removes casting after 9 mins or so.
Can you please tell me why that happened?
Thanks

**Comment by b0mbays** [comment]
Sounds good. This could also just be a network issue.

Why would the hubs remove casting after 9 mins? If there are no interuptions, it will remain. That is what ha-catt-fix does 👍

**Comment by maxakash** [comment]
But I have noticed that all my nest hubs goes to main screen(showing wallpaper) from HA dashboard  and then HA dashboard is recasted within seconds.

**Comment by b0mbays** [comment]
Closing issue as it's most likely a networking issue. If anyone has is experiencing the same issue, please comment below with your logs and I'll re-open to investigate 👍

**Comment by maxakash** [comment]
Hi @b0mbays 
Can I play a sound when doorbell rings while HA is casted on Nest Hubs without interrupting casting?
Thanks
