### ISSUE TITLE
Volume is being set to 0 by default.

### ISSUE THREAD

**Issue by skewll** [b0mbays/continuously_casting_dashboards#55]
When casting to Google Hub Max, with no volume option in yaml, it's still setting volume on each cast to 0 by default it seems.

**Comment by b0mbays** [comment]
Hey @skewll that's correct. The casting process usually creates a "bing" on the device, so we set the volume to the lowest before casting and then restore the volume (if supported by the device and sometimes fails) after the noise occurs. 

If it's not restoring the volume, you can define a volume number per device to set 👍

**Comment by skewll** [comment]
Okay, It doesn't seem to remember the volume on the Google Hub Max so I will figure out another way to preserve the volume state. Thanks!
