### ISSUE TITLE
annoying sound when transmission stops

### ISSUE THREAD

**Issue by goldrake1981** [b0mbays/continuously_casting_dashboards#56]
Hello and congratulations on the project. maybe someone can help me but I have a problem when the interface stops transmitting. basically the nest hub makes a sound, a kind of bell which is very annoying at night, I realized that it doesn't always do it.

**Comment by b0mbays** [comment]
The sound occurs when the dashboard stops? That shouldn't be happening.. what generation display are you using? There should be a very quiet sound that occurs when the dashboard is cast, but that should be it.

**Comment by goldrake1981** [comment]
I have 3 hubs, 2 second generation and 1 first generation it does it on all three.

**Comment by b0mbays** [comment]
Could you take a video of this and upload it here? Thanks!

**Comment by goldrake1981** [comment]
the problem is that it is completely random. I don't know when it gives it.

**Comment by b0mbays** [comment]
Closing issue, will investigate if other users are reporting the same or we have a video of the sound 👍

**Comment by goldrake1981** [comment]
I canceled the volume level line and this strange noise and disappeared. the problem is that I have the volume on 1 when the casting starts
