### ISSUE TITLE
Interupt spotify playing

### ISSUE THREAD

**Issue by Lekskog** [b0mbays/continuously_casting_dashboards#57]
When i listen to spotify it will interupt the music i play and cast the dashboard sometimes directly sometime after a 2-3 songs.

Update:
It also recasting the dashboard 
Here is the config file i have setup:

#Casta till Hubben
continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
  start_time: "06:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
  end_time: "22:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
  devices:
    "Hubben": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
      - dashboard_url: "http://192.168.1.47:8123/lovelace/cast/?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
        volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
        start_time: "06:00" #Optional: Set the start time for this device
        end_time: "22:00" #Optional: Set the end time for this device

**Comment by b0mbays** [comment]
Do you have just one display? I have seen this issue on mine very rarely. I think the issue is the check is checking the display so frequently that in-between songs the device is reporting "not playing" and if you only have one device, then it will be continuously checking and will eventually fall in-between a song.

I'll make a change to delay the check to avoid this from happening

**Comment by Lekskog** [comment]
> Do you have just one display? I have seen this issue on mine very rarely. I think the issue is the check is checking the display so frequently that in-between songs the device is reporting "not playing" and if you only have one device, then it will be continuously checking and will eventually fall in-between a song.
> 
> I'll make a change to delay the check to avoid this from happening

I have multiple chromecast devices but only one nest hub I cast to. It starts in the middle of the song.

**Comment by wimpie007** [comment]
I have the same issue.
Only one nest display, and casting HA screen works fine.
BUT, when playing music with spotify or TuneIn (radio), it stops playing after x seconds and restarts casting HA screen.

**Comment by b0mbays** [comment]
I'll take a look later and try and fix this issue. Apologies!

**Comment by wimpie007** [comment]
tried different versions, 1.26, 1.30, all the same problem.
Casting takes over after 10-30 seconds.
No need for apologies! appreciate your work!

**Comment by wimpie007** [comment]
Thanks man!! That will be the problem indeed... Appreciate your work!

**Comment by b0mbays** [comment]
Hi @Lekskog i've made the media check more robust and reliable in the latest release [v1.3.3](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.3.3) - If you restart HA and update you should not face this issue anymore 👍

**Comment by Lekskog** [comment]
> Hi @Lekskog i've made the media check more robust and reliable in the latest release [v1.3.3](https://github.com/b0mbays/continuously_casting_dashboards/releases/tag/v1.3.3) - If you restart HA and update you should not face this issue anymore 👍

Awesome will see if I can try it out this weekend!
