### ISSUE TITLE
Screen saver

### ISSUE THREAD

**Issue by leirum1980** [b0mbays/continuously_casting_dashboards#69]
Is there a way to install a screen protector? All day showing the same dashboard will end up burning the screen of our Google Nest. Thank you!

**Comment by b0mbays** [comment]
Unfortunately we can't directly dim the Google Nest Hubs through the integration. There might be a way of slightly moving the dashboard around by a few pixels? I haven't looked into that though.

Or you could set the timings to be less if you are worried about it.

However, I've had mine 'continuously' casting for over 18 months to 5 Hubs from 7am to 2am and I've had no burn in 👍
