### ISSUE TITLE
Casting options without menu-items

### ISSUE THREAD

**Issue by Takst3in** [b0mbays/continuously_casting_dashboards#9]
Hi! It all works fine now, casting a unique view to 3 different devices.

However, the menu-bars (marked red in picture) are a bit annoying, can these be removed by any options?

Not sure it its the correct place to ask, but I'll Try..

![IMG_20230413_212316](https://user-images.githubusercontent.com/59628163/231862563-d15d02e4-e024-43cc-9ac3-1c7ac500b670.jpg)

**Comment by Takst3in** [comment]
Resolved... Did not realize at first that the "URL+?kiosk" required an HACS plugin named "kiosk-mode". Installed, and all OK.

**Comment by b0mbays** [comment]
Hey, yes you can use Kiosk Mode to remove these menu bars 😄 

https://github.com/NemesisRE/kiosk-mode

**Comment by b0mbays** [comment]
Just seen your comment! - Good to hear.

**Comment by b0mbays** [comment]
I'll also add that note to the readme. Thank you
